import { Adviser } from '../models/adviser.model';
import { Client } from '../models/client.model';
import { Relationship } from '../models/relationship.model';
import { Goal } from '../models/goal.model';
import { Asset, Liability } from '../models/capital.model';

export interface SeedData {
  advisers: Adviser[];
  clients: Client[];
  relationships: Relationship[];
  goals: Goal[];
  assets: Asset[];
  liabilities: Liability[];
}

export function buildSeedData(): SeedData {
  const now = new Date().toISOString();

  const advisers: Adviser[] = [
    { id: 1, firstName: 'Eleanor', lastName: 'Whitlock', email: 'eleanor.whitlock@padua.example', initials: 'EW' },
    { id: 2, firstName: 'Marcus', lastName: 'Tan', email: 'marcus.tan@padua.example', initials: 'MT' },
    { id: 3, firstName: 'Priya', lastName: 'Singh', email: 'priya.singh@padua.example', initials: 'PS' },
    { id: 4, firstName: 'Jonathan', lastName: 'Reyes', email: 'jonathan.reyes@padua.example', initials: 'JR' },
  ];

  const clients: Client[] = [
    {
      id: 1001,
      title: 'Mr',
      firstName: 'Aaron',
      middleName: 'James',
      lastName: 'Johnson',
      preferredName: 'AJ',
      dateOfBirth: '1975-04-12',
      sex: 'Male',
      maritalStatus: 'Married',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: 'aaron.johnson@example.com',
      phones: [
        { id: 'p-1001-1', kind: 'mobile', number: '+61 400 111 222' },
        { id: 'p-1001-2', kind: 'work', number: '+61 2 9000 1111' },
      ],
      addresses: [
        {
          id: 'a-1001-1',
          kind: 'residential',
          street: '14 Harbour Lane',
          suburb: 'Mosman',
          state: 'NSW',
          postcode: '2088',
          country: 'Australia',
        },
      ],
      occupation: 'Surgeon',
      employer: 'Sydney Private Hospital',
      employmentStatus: 'Employed',
      annualIncome: 480000,
      entityType: 'Individual',
      riskProfile: 'Growth',
      primaryAdviserId: 1,
      secondaryAdviserId: 2,
      status: 'Active',
      createdAt: '2023-02-14T10:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 1002,
      title: 'Mrs',
      firstName: 'Sarah',
      middleName: 'Louise',
      lastName: 'Johnson',
      preferredName: 'Sarah',
      dateOfBirth: '1977-09-22',
      sex: 'Female',
      maritalStatus: 'Married',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: 'sarah.johnson@example.com',
      phones: [{ id: 'p-1002-1', kind: 'mobile', number: '+61 400 333 444' }],
      addresses: [
        {
          id: 'a-1002-1',
          kind: 'residential',
          street: '14 Harbour Lane',
          suburb: 'Mosman',
          state: 'NSW',
          postcode: '2088',
          country: 'Australia',
        },
      ],
      occupation: 'Architect',
      employer: 'Whitlam & Co',
      employmentStatus: 'Self-employed',
      annualIncome: 220000,
      entityType: 'Individual',
      riskProfile: 'Balanced',
      primaryAdviserId: 1,
      secondaryAdviserId: null,
      status: 'Active',
      createdAt: '2023-02-14T10:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 1003,
      title: 'Miss',
      firstName: 'Mia',
      middleName: '',
      lastName: 'Johnson',
      preferredName: 'Mia',
      dateOfBirth: '2010-06-03',
      sex: 'Female',
      maritalStatus: 'Single',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: '',
      phones: [],
      addresses: [
        {
          id: 'a-1003-1',
          kind: 'residential',
          street: '14 Harbour Lane',
          suburb: 'Mosman',
          state: 'NSW',
          postcode: '2088',
          country: 'Australia',
        },
      ],
      occupation: 'Student',
      employer: '',
      employmentStatus: 'Student',
      annualIncome: 0,
      entityType: 'Individual',
      riskProfile: 'Conservative',
      primaryAdviserId: 1,
      secondaryAdviserId: null,
      status: 'Active',
      createdAt: '2023-02-14T10:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 1004,
      title: 'Dr',
      firstName: 'Lachlan',
      middleName: 'Henry',
      lastName: 'O’Connor',
      preferredName: 'Lachie',
      dateOfBirth: '1968-11-30',
      sex: 'Male',
      maritalStatus: 'Divorced',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: 'lachlan.oconnor@example.com',
      phones: [{ id: 'p-1004-1', kind: 'mobile', number: '+61 411 555 666' }],
      addresses: [
        {
          id: 'a-1004-1',
          kind: 'residential',
          street: '8 Riverside Drive',
          suburb: 'South Yarra',
          state: 'VIC',
          postcode: '3141',
          country: 'Australia',
        },
        {
          id: 'a-1004-2',
          kind: 'work',
          street: 'Level 14, 530 Collins Street',
          suburb: 'Melbourne',
          state: 'VIC',
          postcode: '3000',
          country: 'Australia',
        },
      ],
      occupation: 'Dentist',
      employer: 'Yarra Dental Group',
      employmentStatus: 'Self-employed',
      annualIncome: 350000,
      entityType: 'Sole Trader',
      riskProfile: 'Aggressive',
      primaryAdviserId: 2,
      secondaryAdviserId: 4,
      status: 'Active',
      createdAt: '2022-11-01T09:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 1005,
      title: 'Ms',
      firstName: 'Hannah',
      middleName: 'Grace',
      lastName: 'Patel',
      preferredName: 'Han',
      dateOfBirth: '1990-01-18',
      sex: 'Female',
      maritalStatus: 'De facto',
      countryOfResidence: 'Australia',
      citizenship: 'Indian',
      taxResidency: 'Australia',
      email: 'hannah.patel@example.com',
      phones: [{ id: 'p-1005-1', kind: 'mobile', number: '+61 422 777 888' }],
      addresses: [
        {
          id: 'a-1005-1',
          kind: 'residential',
          street: '202/45 Bay Street',
          suburb: 'Brighton',
          state: 'VIC',
          postcode: '3186',
          country: 'Australia',
        },
      ],
      occupation: 'Software Engineer',
      employer: 'Atlassian',
      employmentStatus: 'Employed',
      annualIncome: 195000,
      entityType: 'Individual',
      riskProfile: 'Growth',
      primaryAdviserId: 3,
      secondaryAdviserId: null,
      status: 'Prospect',
      createdAt: '2024-08-21T14:30:00.000Z',
      updatedAt: now,
    },
    {
      id: 1006,
      title: 'Mr',
      firstName: 'David',
      middleName: '',
      lastName: 'Chen',
      preferredName: 'Dave',
      dateOfBirth: '1988-07-09',
      sex: 'Male',
      maritalStatus: 'De facto',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: 'david.chen@example.com',
      phones: [{ id: 'p-1006-1', kind: 'mobile', number: '+61 433 999 000' }],
      addresses: [
        {
          id: 'a-1006-1',
          kind: 'residential',
          street: '202/45 Bay Street',
          suburb: 'Brighton',
          state: 'VIC',
          postcode: '3186',
          country: 'Australia',
        },
      ],
      occupation: 'Lawyer',
      employer: 'Allens',
      employmentStatus: 'Employed',
      annualIncome: 240000,
      entityType: 'Individual',
      riskProfile: 'Balanced',
      primaryAdviserId: 3,
      secondaryAdviserId: null,
      status: 'Prospect',
      createdAt: '2024-08-21T14:30:00.000Z',
      updatedAt: now,
    },
    {
      id: 1007,
      title: 'Mr',
      firstName: 'William',
      middleName: 'George',
      lastName: 'Carter',
      preferredName: 'Will',
      dateOfBirth: '1955-03-15',
      sex: 'Male',
      maritalStatus: 'Widowed',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: 'will.carter@example.com',
      phones: [{ id: 'p-1007-1', kind: 'home', number: '+61 2 9888 7777' }],
      addresses: [
        {
          id: 'a-1007-1',
          kind: 'residential',
          street: '7 Coastal Way',
          suburb: 'Manly',
          state: 'NSW',
          postcode: '2095',
          country: 'Australia',
        },
      ],
      occupation: 'Retired Engineer',
      employer: '',
      employmentStatus: 'Retired',
      annualIncome: 65000,
      entityType: 'Individual',
      riskProfile: 'Conservative',
      primaryAdviserId: 4,
      secondaryAdviserId: null,
      status: 'Active',
      createdAt: '2021-05-12T11:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 1008,
      title: 'Mrs',
      firstName: 'Carter',
      middleName: '',
      lastName: 'Family Trust',
      preferredName: 'Carter Trust',
      dateOfBirth: '2010-01-01',
      sex: 'Prefer not to say',
      maritalStatus: 'Single',
      countryOfResidence: 'Australia',
      citizenship: 'Australian',
      taxResidency: 'Australia',
      email: '',
      phones: [],
      addresses: [],
      occupation: '',
      employer: '',
      employmentStatus: 'Home duties',
      annualIncome: 0,
      entityType: 'Trust',
      riskProfile: 'Balanced',
      primaryAdviserId: 4,
      secondaryAdviserId: null,
      status: 'Active',
      createdAt: '2021-06-01T11:00:00.000Z',
      updatedAt: now,
    },
  ];

  const relationships: Relationship[] = [
    { id: 'r-1', fromClientId: 1001, toClientId: 1002, type: 'Spouse' },
    { id: 'r-2', fromClientId: 1001, toClientId: 1003, type: 'Dependent', dependentKind: 'Child' },
    { id: 'r-3', fromClientId: 1002, toClientId: 1003, type: 'Dependent', dependentKind: 'Child' },
    { id: 'r-4', fromClientId: 1005, toClientId: 1006, type: 'Spouse' },
    { id: 'r-5', fromClientId: 1007, toClientId: 1008, type: 'Trust Trustee' },
  ];

  const goals: Goal[] = [
    {
      id: 'g-1',
      clientId: 1001,
      title: 'Retire at 60',
      description: 'Build sufficient capital to retire comfortably at age 60.',
      category: 'Retirement',
      priority: 'High',
      status: 'On Track',
      targetAmount: 3500000,
      currentAmount: 1450000,
      timeFrameMode: 'special',
      targetDate: null,
      specialDateOption: 'By Retirement',
      completed: false,
      outcomeNotes: null,
      completionDate: null,
      createdAt: '2023-03-01T00:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'g-2',
      clientId: 1001,
      title: "Mia's university fund",
      description: 'Save for Mia’s tertiary education.',
      category: 'Education',
      priority: 'Medium',
      status: 'In Progress',
      targetAmount: 200000,
      currentAmount: 65000,
      timeFrameMode: 'date',
      targetDate: '2028-01-31',
      specialDateOption: null,
      completed: false,
      outcomeNotes: null,
      completionDate: null,
      createdAt: '2023-03-01T00:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'g-3',
      clientId: 1001,
      title: 'Pay off home loan',
      description: 'Eliminate primary residence mortgage ahead of schedule.',
      category: 'Debt Reduction',
      priority: 'High',
      status: 'On Track',
      targetAmount: 850000,
      currentAmount: 320000,
      timeFrameMode: 'special',
      targetDate: null,
      specialDateOption: 'Medium Term',
      completed: false,
      outcomeNotes: null,
      completionDate: null,
      createdAt: '2023-03-01T00:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'g-4',
      clientId: 1001,
      title: 'Family trip to Europe',
      description: '6-week European holiday with the family.',
      category: 'Travel',
      priority: 'Low',
      status: 'On Track',
      targetAmount: 60000,
      currentAmount: 60000,
      timeFrameMode: 'date',
      targetDate: '2024-06-15',
      specialDateOption: null,
      completed: true,
      outcomeNotes: 'Completed under budget. Spent 4 weeks instead of 6 due to work commitments.',
      completionDate: '2024-07-30',
      createdAt: '2023-01-01T00:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'g-5',
      clientId: 1004,
      title: 'Sell dental practice',
      description: 'Prepare practice for sale within 5 years and execute exit.',
      category: 'Business',
      priority: 'High',
      status: 'In Progress',
      targetAmount: 2500000,
      currentAmount: 0,
      timeFrameMode: 'special',
      targetDate: null,
      specialDateOption: 'Long Term',
      completed: false,
      outcomeNotes: null,
      completionDate: null,
      createdAt: '2023-06-01T00:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'g-6',
      clientId: 1007,
      title: 'Estate plan and gifting',
      description: 'Establish estate plan and structured gifting for grandchildren.',
      category: 'Legacy',
      priority: 'High',
      status: 'On Track',
      targetAmount: 500000,
      currentAmount: 150000,
      timeFrameMode: 'special',
      targetDate: null,
      specialDateOption: 'Ongoing',
      completed: false,
      outcomeNotes: null,
      completionDate: null,
      createdAt: '2023-09-01T00:00:00.000Z',
      updatedAt: now,
    },
  ];

  const assets: Asset[] = [
    {
      id: 'as-1',
      ownerClientId: 1001,
      name: 'Mosman Family Home',
      type: 'Property',
      currentValue: 4200000,
      purchaseValue: 2750000,
      purchaseDate: '2014-08-01',
      ownershipPercentage: 50,
      linked_liability_id: 'li-1',
    },
    {
      id: 'as-2',
      ownerClientId: 1002,
      name: 'Mosman Family Home',
      type: 'Property',
      currentValue: 4200000,
      purchaseValue: 2750000,
      purchaseDate: '2014-08-01',
      ownershipPercentage: 50,
      linked_liability_id: 'li-1',
    },
    {
      id: 'as-3',
      ownerClientId: 1001,
      name: 'AustralianSuper Balanced',
      type: 'Superannuation',
      currentValue: 980000,
      purchaseValue: 0,
      purchaseDate: '2000-01-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-4',
      ownerClientId: 1002,
      name: 'Hostplus Indexed',
      type: 'Superannuation',
      currentValue: 540000,
      purchaseValue: 0,
      purchaseDate: '2002-03-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-5',
      ownerClientId: 1001,
      name: 'CommSec Share Portfolio',
      type: 'Shares',
      currentValue: 360000,
      purchaseValue: 220000,
      purchaseDate: '2018-04-15',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-6',
      ownerClientId: 1001,
      name: 'Cash at bank',
      type: 'Cash',
      currentValue: 85000,
      purchaseValue: 85000,
      purchaseDate: '2024-01-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-7',
      ownerClientId: 1004,
      name: 'South Yarra Apartment',
      type: 'Property',
      currentValue: 1850000,
      purchaseValue: 1450000,
      purchaseDate: '2017-02-01',
      ownershipPercentage: 100,
      linked_liability_id: 'li-3',
    },
    {
      id: 'as-8',
      ownerClientId: 1004,
      name: 'Yarra Dental Group',
      type: 'Business',
      currentValue: 2200000,
      purchaseValue: 1200000,
      purchaseDate: '2010-06-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-9',
      ownerClientId: 1007,
      name: 'Manly Cottage',
      type: 'Property',
      currentValue: 2350000,
      purchaseValue: 380000,
      purchaseDate: '1992-09-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
    {
      id: 'as-10',
      ownerClientId: 1007,
      name: 'Term deposit',
      type: 'Cash',
      currentValue: 250000,
      purchaseValue: 250000,
      purchaseDate: '2024-01-01',
      ownershipPercentage: 100,
      linked_liability_id: null,
    },
  ];

  const liabilities: Liability[] = [
    {
      id: 'li-1',
      ownerClientId: 1001,
      name: 'Mosman Home Loan',
      type: 'Mortgage',
      currentBalance: 850000,
      originalAmount: 1800000,
      interestRate: 5.95,
      monthlyPayment: 6200,
      startDate: '2014-08-01',
      endDate: '2044-08-01',
      linked_asset_id: 'as-1',
    },
    {
      id: 'li-2',
      ownerClientId: 1001,
      name: 'AMEX Platinum',
      type: 'Credit Card',
      currentBalance: 4200,
      originalAmount: 0,
      interestRate: 21.5,
      monthlyPayment: 0,
      startDate: '2018-01-01',
      endDate: null,
      linked_asset_id: null,
    },
    {
      id: 'li-3',
      ownerClientId: 1004,
      name: 'South Yarra Loan',
      type: 'Mortgage',
      currentBalance: 620000,
      originalAmount: 1100000,
      interestRate: 6.15,
      monthlyPayment: 4400,
      startDate: '2017-02-01',
      endDate: '2042-02-01',
      linked_asset_id: 'as-7',
    },
  ];

  return { advisers, clients, relationships, goals, assets, liabilities };
}
